version: '3'
services:
  api:
    build:
      context: ./node
    container_name: api
    restart: always
    command: ["sh", "-c", "./dockerize -wait tcp://db:3306 && node index.js"]
    environment:
      DB_USER: root
      DB_PASS: root
      DB_NAME: test
      DB_PORT: 3306
      DB_HOST: db
    networks:
      - node-network
    depends_on:
      - db
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - api

networks:
  node-network:
    driver: bridge